/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class morgan_natives_NtvGame */

#ifndef _Included_morgan_natives_NtvGame
#define _Included_morgan_natives_NtvGame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     morgan_natives_NtvGame
 * Method:    create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     morgan_natives_NtvGame
 * Method:    pulse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_pulse
  (JNIEnv *, jobject);

/*
 * Class:     morgan_natives_NtvGame
 * Method:    handleMsg
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_handleMsg
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     morgan_natives_NtvGame
 * Method:    addPlayer
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_addPlayer
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     morgan_natives_NtvGame
 * Method:    initGame
 * Signature: ([I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_initGame
  (JNIEnv *, jobject, jintArray, jobjectArray);

/*
 * Class:     morgan_natives_NtvGame
 * Method:    removePlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_removePlayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     morgan_natives_NtvGame
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvGame_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
