/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class morgan_natives_NtvManager */

#ifndef _Included_morgan_natives_NtvManager
#define _Included_morgan_natives_NtvManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     morgan_natives_NtvManager
 * Method:    setNtvFunctions
 * Signature: (Lmorgan/natives/INtvFunctions;)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvManager_setNtvFunctions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     morgan_natives_NtvManager
 * Method:    loadMeshes
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvManager_loadMeshes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     morgan_natives_NtvManager
 * Method:    jniTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_morgan_natives_NtvManager_jniTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
